In [1]:
import numpy as np
#create a sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
U,S,VT =np.linalg.svd(X)
#choose the number of components to keep(e.g.,2)
n_components = 2
# Reconstruct the matrix with reduced dimrntions
X_reconstructed = np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Orginal Matrix")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)

Orginal Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
