In [3]:
import numpy as np
#create matrices
A=np.array([[5,6],[3,4]])
B=np.array([[5,6],[7,8]])
#Addition
C=A+B
#Subtraction
D=A-B
#Multiplication(element-wise)
E=A*B
#Matrix Multiplication
F=np.dot(A, B) # or A @ B
#Transpose
A_transpose=A.T
print("Addition:")
print(C)
print("Subtraction:")
print(D)
print("\nElement-Wise Multiplication:")
print(E)
print("\nMatrix Multiplication:")
print(F)
print("\nTranspose:")
print(A_transpose)

Addition:
[[10 12]
 [10 12]]
Subtraction:
[[ 0  0]
 [-4 -4]]

Element-Wise Multiplication:
[[25 36]
 [21 32]]

Matrix Multiplication:
[[67 78]
 [43 50]]

Transpose:
[[5 3]
 [6 4]]
